//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.Scripting;
    
    
    // Level.xlsx
    [PreserveAttribute()]
    public class MatchLevelTable : ExcelTable<Excel.MatchLevelRecord>
    {
        
        [PreserveAttribute()]
        private Dictionary<int,Excel.MatchLevelRecord> _map = new Dictionary<int,Excel.MatchLevelRecord>();
        
        [PreserveAttribute()]
        public Excel.MatchLevelRecord this[int RoomID]
        {
            get
            {
                Excel.MatchLevelRecord record = null;
                if (!this._map.TryGetValue(RoomID, out record) && RoomID != 0)
                {
                    Debug.LogError((RoomID + " is not found in Excel.MatchLevelRecord"));
                }
                return record;
            }
        }
        
        [PreserveAttribute()]
        protected internal override void CreateDictionary()
        {
            if ((null == this.list))
            {
                return;
            }
            this._map.Clear();
            for (int index = 0; (index < this.list.Count); index = (index + 1))
            {
                Excel.MatchLevelRecord record = this.list[index];
                this._map.Add(record.RoomID, record);
            }
        }
        
        [PreserveAttribute()]
        protected internal override void Clear()
        {
            this._map.Clear();
        }
    }
}
