// //------------------------------------------------------------------------------
// // <auto-generated>
// //     This code was generated by a tool.
// //     Runtime Version:4.0.30319.42000
// //
// //     Changes to this file may cause incorrect behavior and will be lost if
// //     the code is regenerated.
// // </auto-generated>
// //------------------------------------------------------------------------------
//
// namespace Excel
// {
//     using System;
//     using System.Collections;
//     using System.Collections.Generic;
//     using UnityEngine;
//     
//     
//     public partial class ExcelManager
//     {
//         private Excel.AreaNameTable _AreaNameTable = null;
//         private Excel.MatchLevelTable _MatchLevelTable = null;
//         
//         
//         public Excel.AreaNameTable AreaNameTable
//         {
//             geta
//             {
//                 return this._AreaNameTable;
//             }
//         }
//         public Excel.AreaNameTable MatchLevelTable
//         {
//             get
//             {
//                 return this.MatchLevelTable;
//             }
//         }
//         
//     }
// }
