//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    
    
    public enum EPresentationTips
    {
        
        None = 0,
        
        /// <summary>
        /// 该功能暂未开启
        /// </summary>
        TIPS_COMMON_ERROR_NOT_OPEN_FUNCTION = 1,
        
        /// <summary>
        /// 升级成功（测试）
        /// </summary>
        TIPS_COMMON_NORMAL_LEVELUP = 2,
        
        /// <summary>
        /// 获得头像框（测试）
        /// </summary>
        TIPS_COMMON_ITEM_GET_HEAD_PIC_FRAME = 3,
        
        /// <summary>
        /// 道具不足
        /// </summary>
        TIPS_COMMON_ERROR_NOT_ENOUGH_ITEM = 4,
        
        /// <summary>
        /// 金币不足
        /// </summary>
        TIPS_COMMON_ERROR_NOT_ENOUGH_COIN = 5,
        
        /// <summary>
        /// 找不到对应配置
        /// </summary>
        TIPS_COMMON_ERROR_NOT_FOUND_CONFIG = 6,
        
        /// <summary>
        /// 条件不满足
        /// </summary>
        TIPS_COMMON_ERROR_NOT_ENOUGH_CONDITION = 7,
        
        /// <summary>
        /// 装备经验不足
        /// </summary>
        TIPS_COMMON_ERROR_NOT_ENOUGH_EQUIPEXP = 8,
        
        /// <summary>
        /// 角色功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_CHARACTER = 201,
        
        /// <summary>
        /// 角色升级功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_CHARACTER_LEVEL = 202,
        
        /// <summary>
        /// 角色升星功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_CHARACTER_STAR = 203,
        
        /// <summary>
        /// 角色灵力功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_CHARACTER_MANA = 204,
        
        /// <summary>
        /// 角色虚核功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_CHARACTER_EQUIP = 205,
        
        /// <summary>
        /// 背包功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_BACKPACK = 206,
        
        /// <summary>
        /// 通讯器功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_CELLPHONE = 207,
        
        /// <summary>
        /// 共同用餐功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_DINNING = 208,
        
        /// <summary>
        /// 商店功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_SHOP = 209,
        
        /// <summary>
        /// 成就功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_ACHIEVEMENT = 210,
        
        /// <summary>
        /// 任务功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_MISSION = 211,
        
        /// <summary>
        /// 副本功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_DUNGEON = 212,
        
        /// <summary>
        /// 抽卡功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_GACHA = 213,
        
        /// <summary>
        /// 编队功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_TEAMBUILD = 214,
        
        /// <summary>
        /// 巡演功能开启
        /// </summary>
        TIPS_COMMON_UNLOCK_SYSTEM_TOUR = 215,
        
        /// <summary>
        /// 还未到你的回合
        /// </summary>
        TIPS_HANAFUDA_WAIT_CODE = 216,
        
        /// <summary>
        /// 升级成功
        /// </summary>
        TIPS_CHARACTER_NORMAL_LEVELUP_SUCCESS = 100001,
        
        /// <summary>
        /// 升星成功
        /// </summary>
        TIPS_CHARACTER_NORMAL_STAR_SUCCESS = 100002,
        
        /// <summary>
        /// 当前还未达到等级上限，无法进行升星，需先前往升级
        /// </summary>
        TIPS_CHARACTER_ERROR_NEED_LEVEL = 100100,
        
        /// <summary>
        /// 角色信息不存在
        /// </summary>
        TIPS_CHARACTER_ERROR_CHARACTER_NOT_FOUND = 100101,
        
        /// <summary>
        /// 角色等级已经达到最大
        /// </summary>
        TIPS_CHARACTER_ERROR_REACH_MAX_LEVEL = 100102,
        
        /// <summary>
        /// 角色当前的星级对应的等级已经达到最大
        /// </summary>
        TIPS_CHARACTER_ERROR_STAR_LEVEL_LIMIT = 100103,
        
        /// <summary>
        /// 角色升级时，角色经验不足
        /// </summary>
        TIPS_CHARACTER_ERROR_UPGRADE_NOT_ENOUGH_EXP = 100104,
        
        /// <summary>
        /// 角色星级已经达到最大
        /// </summary>
        TIPS_CHARACTER_ERROR_REACH_MAX_STAR = 100105,
        
        /// <summary>
        /// 达到最大觉醒等级
        /// </summary>
        TIPS_MANA_ERROR_AWAKE_LEVEL_MAX = 100106,
        
        /// <summary>
        /// 强化时没有达到最大觉醒等级
        /// </summary>
        TIPS_MANA_ERROR_NOT_REACH_MAX_AWAKE_LEVEL = 100201,
        
        /// <summary>
        /// 灵力强化时，灵力节点已解锁
        /// </summary>
        TIPS_MANA_ERROR_STRENGTHEN_NODE_UNLOCKED = 100202,
        
        /// <summary>
        /// 灵力强化时，前置节点未解锁
        /// </summary>
        TIPS_MANA_ERROR_PRE_STRENGTHEN_NODE_LOCKED = 100203,
        
        /// <summary>
        /// 不能将高级材料转化成低级材料
        /// </summary>
        TIPS_MANA_ERROR_NOT_TRANSFERRED = 100204,
        
        /// <summary>
        /// 转化的材料数量不合法
        /// </summary>
        TIPS_MANA_ERROR_INVALID_TRANSFERER = 100205,
        
        /// <summary>
        /// 灵力强化时，未满足条件
        /// </summary>
        TIPS_MANA_ERROR_STRENGTHEN_UNMET = 100206,
        
        /// <summary>
        /// 当前部分暂不可进行觉醒
        /// </summary>
        TIPS_MANA_ERROR_SELECT_PART_NOT_AWAKE = 100207,
        
        /// <summary>
        /// 激活成功
        /// </summary>
        TIPS_MANA_NORMAL_ACTIVATE = 100208,
        
        /// <summary>
        /// 请至少确定两名主要角色
        /// </summary>
        TIPS_TOUR_ERROR_START_MEMBER = 400001,
        
        /// <summary>
        /// 出演队伍已达到上限
        /// </summary>
        TIPS_TOUR_ERROR_LIMIT_MEMBER = 400002,
        
        /// <summary>
        /// 已经派遣出去的角色
        /// </summary>
        TIPS_TOUR_ERROR_SENT_MEMBER = 400003,
        
        /// <summary>
        /// 没有对应角色
        /// </summary>
        TIPS_TOUR_ERROR_NO_MEMBER = 400004,
        
        /// <summary>
        /// 抽卡道具不足
        /// </summary>
        TIPS_GACHA_ERROR_NO_DRAW_ITEM = 410001,
        
        /// <summary>
        /// 兑换点数不足
        /// </summary>
        TIPS_GACHA_ERROR_NO_CEIL_ITEM = 410002,
        
        /// <summary>
        /// 请滑动或双击一张想要的卡片
        /// </summary>
        TIPS_RYO_GACHA_HINT_CHOOSE_CARD = 410003,
        
        /// <summary>
        /// 当前牌册可召唤次数不足10次，请进行单次召唤
        /// </summary>
        TIPS_GACHA_TIPS_CANNOT_TEN_DRAW = 410004,
        
        /// <summary>
        /// 副本暂未开启
        /// </summary>
        TIPS_DUNGEON_ERROR_LOCKED = 420001,
        
        /// <summary>
        /// 可扫荡的次数不足
        /// </summary>
        TIPS_OTHER_COMMON_SHORTCUT_TIMES_NOT_ENOUGH = 420002,
        
        /// <summary>
        /// 商店参数错误
        /// </summary>
        TIPS_STORE_ERROR_INVALID_PARAMS = 500001,
        
        /// <summary>
        /// 该商店中没有对应商品
        /// </summary>
        TIPS_STORE_ERROR_SKU_NOT_IN_STORE = 500002,
        
        /// <summary>
        /// 价格有误
        /// </summary>
        TIPS_STORE_ERROR_INVALID_PRICE = 500003,
        
        /// <summary>
        /// 消耗品类型有误
        /// </summary>
        TIPS_STORE_ERROR_INVALID_CONSUME_TYPE = 500004,
        
        /// <summary>
        /// 商店歇业中
        /// </summary>
        TIPS_STORE_ERROR_STORE_CLOSED = 500005,
        
        /// <summary>
        /// 该商品不在有效开放时间内
        /// </summary>
        TIPS_STORE_ERROR_SKU_INACTIVE = 500006,
        
        /// <summary>
        /// 该商品已超过购买上限限制
        /// </summary>
        TIPS_STORE_ERROR_REACH_PURCHASE_LIMIT = 500007,
        
        /// <summary>
        /// 未达到指定等级
        /// </summary>
        TIPS_STORE_ERROR_LEVEL_NOT_QUALIFIED = 500008,
        
        /// <summary>
        /// 商店刷新次数达到上限
        /// </summary>
        TIPS_STORE_ERROR_REACH_MAX_REFRESH_TIMES = 500009,
        
        /// <summary>
        /// 请先选择您想要获得的物品
        /// </summary>
        TIPS_SELECT_BUNDLE_NOT_CHOSE = 500010,
        
        /// <summary>
        /// 达到最大的批量发送邮件数量
        /// </summary>
        TIPS_MAIL_ERROR_MAX_SEND_NUM = 600001,
        
        /// <summary>
        /// 邮件不存在
        /// </summary>
        TIPS_MAIL_ERROR_MAIL_NOT_EXIST = 600002,
        
        /// <summary>
        /// 当前没有可领取的邮件
        /// </summary>
        TIPS_MAIL_ERROR_NO_REWARD_MAIL = 600003,
        
        /// <summary>
        /// 当前没有可删除的邮件
        /// </summary>
        TIPS_MAIL_ERROR_NOT_DELETE_MAIL = 600004,
        
        /// <summary>
        /// 邮件删除成功
        /// </summary>
        TIPS_MAIL_NORMAL_DELETE_SUCCESS = 600005,
        
        /// <summary>
        /// 道具超过上限，当前邮件不能领取
        /// </summary>
        TIPS_OTHER_ALINA_MAIL_NOT_GET = 600006,
        
        /// <summary>
        /// 账户昵称格式不合法
        /// </summary>
        TIPS_LOGIN_ERROR_NICKNAME_INVALID = 700000,
        
        /// <summary>
        /// 账户昵称重复
        /// </summary>
        TIPS_LOGIN_ERROR_NICKNAME_REPEATITION = 700001,
        
        /// <summary>
        /// 账户在黑名单中
        /// </summary>
        TIPS_LOGIN_ERROR_NICKNAME_IN_BLACKLIST = 700002,
        
        /// <summary>
        /// 账户昵称非法（昵称不在白名单中）
        /// </summary>
        TIPS_LOGIN_ERROR_NICKNAME_OUT_WHITELIST = 700003,
        
        /// <summary>
        /// 账户信息不存在
        /// </summary>
        TIPS_LOGIN_ERROR_ACCOUNT_INEXISTENCE = 700004,
        
        /// <summary>
        /// 账户昵称长度不合法
        /// </summary>
        TIPS_LOGIN_ERROR_NICKNAME_BEYOND_LENGTH = 700005,
        
        /// <summary>
        /// 该账户已存在
        /// </summary>
        TIPS_LOGIN_ERROR_ACCOUNT_EXISTED = 700006,
        
        /// <summary>
        /// 账户扩展索引信息不存在
        /// </summary>
        TIPS_LOGIN_ERROR_ACCOUNT_INFO_INEXISTENCE = 700007,
        
        /// <summary>
        /// 创建主角时，已存在主角id
        /// </summary>
        TIPS_LOGIN_ERROR_MAIN_CHARACTER_EXISTED = 700008,
        
        /// <summary>
        /// 该登录地区未开放
        /// </summary>
        TIPS_LOGIN_ERROR_SERVER_CLOSE = 800000,
        
        /// <summary>
        /// 该地区不可用（通知地址为空）
        /// </summary>
        TIPS_LOGIN_ERROR_SERVER_DEFAULT = 800001,
        
        /// <summary>
        /// 请先阅读和勾选同意用户协议
        /// </summary>
        TIPS_LOGIN_ERROR_SERVER_PRIVACY = 800002,
        
        /// <summary>
        /// 恋爱卡牌重复
        /// </summary>
        TIPS_OTHER_DATING_DUPLICATE_LOVE_CARD = 900000,
        
        /// <summary>
        /// 恋爱卡牌不存在
        /// </summary>
        TIPS_OTHER_DATING_LOVE_CARD_NOT_FOUND = 900001,
        
        /// <summary>
        /// 恋爱卡牌的位置不合法
        /// </summary>
        TIPS_OTHER_DATING_INVALID_POSTION = 900002,
        
        /// <summary>
        /// 卡组的卡牌数量超过最大值
        /// </summary>
        TIPS_OTHER_DATING_REACH_CARD_GROUPS_NUM_LIMIT = 900003,
        
        /// <summary>
        /// 卡组的卡牌数量小于最小值
        /// </summary>
        TIPS_OTHER_DATING_LESS_CARD_GROUPS_NUM_LIMIT = 900004,
        
        /// <summary>
        /// 卡组的 cost 值达到上限
        /// </summary>
        TIPS_OTHER_DATING_REACH_CARD_GROUPS_COST_LIMIT = 900005,
        
        /// <summary>
        /// 恋爱卡牌等级已达到最大
        /// </summary>
        TIPS_OTHER_DATING_REACH_CARD_MAX_LEVEL = 900006,
        
        /// <summary>
        /// 好感度等级未达到最低要求等级
        /// </summary>
        TIPS_OTHER_DATING_LESS_MIN_LOVE_LEVEL = 900007,
        
        /// <summary>
        /// 该角色已经被邀请了
        /// </summary>
        TIPS_OTHER_DATING_ROLE_HAS_BEEN_INVITED = 900008,
        
        /// <summary>
        /// 已经邀请了其他角色
        /// </summary>
        TIPS_OTHER_DATING_HAS_INVITED_OTHER_ROLE = 900009,
        
        /// <summary>
        /// 约会时间未到
        /// </summary>
        TIPS_OTHER_DATING_DATING_TIME_NOT_ARRIVE = 900010,
        
        /// <summary>
        /// 该角色处于爽约期
        /// </summary>
        TIPS_OTHER_DATING_ROLE_IN_UNHAPPY_TIME = 900011,
        
        /// <summary>
        /// 该角色未被邀请
        /// </summary>
        TIPS_OTHER_DATING_ROLE_NOT_INVITED = 900012,
        
        /// <summary>
        /// 该角色没有处于约会中
        /// </summary>
        TIPS_OTHER_DATING_ROLE_NOT_IN_DATING = 900013,
        
        /// <summary>
        /// 不能开启快速约会（没有被邀请或者约会时间未到）
        /// </summary>
        TIPS_OTHER_DATING_CAN_NOT_QUICK_DATING = 900014,
        
        /// <summary>
        /// 快速约会没有达到相应的约会评级
        /// </summary>
        TIPS_OTHER_DATING_NOT_REACH_RANK_LEVEL = 900015,
        
        /// <summary>
        /// 该角色不允许被约会
        /// </summary>
        TIPS_OTHER_DATING_ROLE_NOT_ALLOWED = 900016,
        
        /// <summary>
        /// 好感度等级达到上限
        /// </summary>
        TIPS_OTHER_AFFECTION_REACH_LEVEL_LIMIT = 1000000,
        
        /// <summary>
        /// 平台好感度等级达到上限
        /// </summary>
        TIPS_OTHER_AFFECTION_PLATFORM_LEVEL_REACH_MAX = 1000001,
        
        /// <summary>
        /// 没有可领取的好感度任务奖励
        /// </summary>
        TIPS_OTHER_AFFECTION_NO_TASK_REWARDS = 1000002,
        
        /// <summary>
        /// 领取好感度任务奖励失败
        /// </summary>
        TIPS_OTHER_AFFECTION_GIVE_TASK_REWARDS_FAILED = 1000003,
        
        /// <summary>
        /// 角色间的好感度信息不存在
        /// </summary>
        TIPS_OTHER_AFFECTION_INFO_NOT_FOUND = 1000004,
        
        /// <summary>
        /// 未到达要求等级无法领取
        /// </summary>
        TIPS_OTHER_COCO_UI_LOVE_TIP_AWARD_LOCKED = 1000005,
        
        /// <summary>
        /// 菜式数量不合法
        /// </summary>
        TIPS_OTHER_DINING_INVALID_DISH_COUNT = 1100000,
        
        /// <summary>
        /// 提交预订单时，预订单状态不处于初始状态
        /// </summary>
        TIPS_OTHER_DINING_ORDER_STATE_NOT_IN_INITIAL = 1100001,
        
        /// <summary>
        /// 邀请用餐时，预订单状态不处于已预订状态
        /// </summary>
        TIPS_OTHER_DINING_ORDER_STATE_NOT_IN_ORDERED = 1100002,
        
        /// <summary>
        /// 开始用餐时，预订单状态不处于已邀请状态
        /// </summary>
        TIPS_OTHER_DINING_ORDER_STATE_NOT_IN_INVITED = 1100003,
        
        /// <summary>
        /// 取消用餐或用餐结算时，预订单状态不处于用餐中状态
        /// </summary>
        TIPS_OTHER_DINING_ORDER_STATE_NOT_IN_DINING = 1100004,
        
        /// <summary>
        /// 座位号重复
        /// </summary>
        TIPS_OTHER_DINING_DUPLICATE_SEAT_ID = 1100005,
        
        /// <summary>
        /// 非法的用餐角色
        /// </summary>
        TIPS_OTHER_DINING_INVALID_DINING_ROLES = 1100006,
        
        /// <summary>
        /// 快速用餐没有达到用餐等级
        /// </summary>
        TIPS_OTHER_DINING_NOT_REACH_RANK_LEVEL = 1100007,
        
        /// <summary>
        /// 角色不允许用餐
        /// </summary>
        TIPS_OTHER_DINING_ROLE_NOT_ALLOWED = 1100008,
        
        /// <summary>
        /// 升级时，势力等级已达到最大级
        /// </summary>
        TIPS_ACH_ERROR_MAX = 1200000,
        
        /// <summary>
        /// 升级时，成就点数不足
        /// </summary>
        TIPS_ACH_ERROR_LACK_POINT = 1200001,
        
        /// <summary>
        /// 势力故事解锁时，该故事已经解锁了
        /// </summary>
        TIPS_ACH_ERROR_STORY_UNLOCKED = 1200002,
        
        /// <summary>
        /// 领取成就奖励时，没有成就奖励可领
        /// </summary>
        TIPS_ACH_ERROR_NO_REWARDS = 1200003,
        
        /// <summary>
        /// 领取成就奖励失败
        /// </summary>
        TIPS_ACH_ERROR_FAILURE = 1200004,
        
        /// <summary>
        /// 任务没有处于完成状态
        /// </summary>
        TIPS_TASK_ERROR_UNFINISHED = 1300000,
        
        /// <summary>
        /// 任务未找到
        /// </summary>
        TIPS_TASK_ERROR_UNFOUND = 1300001,
        
        /// <summary>
        /// 晋升时，阶段已达到最大
        /// </summary>
        TIPS_TASK_ERROR_MAX = 1300002,
        
        /// <summary>
        /// 晋升时，存在子任务未领取奖励
        /// </summary>
        TIPS_TASK_ERROR_UNATTAINED = 1300003,
        
        /// <summary>
        /// 领取奖励时，子任务没有处于完成状态
        /// </summary>
        TIPS_TASK_ERROR_SUBTASK_UNFINISHED = 1300004,
        
        /// <summary>
        /// 账户昵称格式不合法
        /// </summary>
        TIPS_TEAM_ERROR_FORMERROR = 1400001,
        
        /// <summary>
        /// 账户昵称重复
        /// </summary>
        TIPS_TEAM_ERROR_DUPLICATE_NAME = 1400002,
        
        /// <summary>
        /// 账户昵称长度不合法
        /// </summary>
        TIPS_TEAM_ERROR_NAMELENGTH = 1400003,
        
        /// <summary>
        /// 头像框不合法
        /// </summary>
        TIPS_TEAM_ERROR_ILLEGAL_HEADFRAME = 1400004,
        
        /// <summary>
        /// 头像不合法
        /// </summary>
        TIPS_TEAM_ERROR_ILLEGAL_HEAD = 1400005,
        
        /// <summary>
        /// 复制成功
        /// </summary>
        TIPS_TEAM_ERROR_NAME_COPED = 1400006,
        
        /// <summary>
        /// 名称未更改
        /// </summary>
        TIPS_TEAM_ERROR_NAME_UNCHANGED = 1400007,
        
        /// <summary>
        /// 体力已满
        /// </summary>
        TIPS_OTHER_RYO_UI_TIPS_TEAM_ENERGY_FULL = 1400008,
        
        /// <summary>
        /// 名称未变更
        /// </summary>
        TIPS_OTHER_RYO_UI_TIPS_TEAM_CHANGE_NAME_NO_CHANGE = 1400009,
        
        /// <summary>
        /// 该队员以进行作战支援，不可重复选择
        /// </summary>
        TIPS_OTHER_35P_TOUR_ERROR_SENT = 1400010,
        
        /// <summary>
        /// 体力已达上限
        /// </summary>
        TIPS_ENERGY_ERROR_REACHLIMIT = 1500001,
        
        /// <summary>
        /// 体力不足
        /// </summary>
        TIPS_ENERGY_ERROR_NO_ENERGY = 1500002,
        
        /// <summary>
        /// 体力购买次数达到上限
        /// </summary>
        TIPS_ENERGY_ERROR_PURCHASELIMIT = 1500003,
        
        /// <summary>
        /// 前置章节未解锁
        /// </summary>
        TIPS_STORY_ERROR_PRECHAPTER_NOT_CLEARED = 1600001,
        
        /// <summary>
        /// 战队等级不足
        /// </summary>
        TIPS_STORY_ERROR_NOT_ENOUGH_TEAMLEVEL = 1600002,
        
        /// <summary>
        /// 需完成当前卷内所有普通难度剧情后解锁
        /// </summary>
        TIPS_STORY_ERROR_HARD_UNLOCK_CONDITION = 1600003,
        
        /// <summary>
        /// 技能升阶成功
        /// </summary>
        TIPS_SKILLUP_SKILL_LEVELUP_SUCCEED = 1700001,
        
        /// <summary>
        /// 无可用装备
        /// </summary>
        TIPS_EQUIP_ERROR_AUTOEQUIP_NO_USEFUL_EQUIP = 1800001,
        
        /// <summary>
        /// 装备格已满
        /// </summary>
        TIPS_EQUIP_ERROR_AUTOEQUIP_FULL = 1800002,
        
        /// <summary>
        /// 自动装备成功
        /// </summary>
        TIPS_EQUIP_NORMAL_AUTOEQUIP_SUCCEED = 1800003,
        
        /// <summary>
        /// 强化成功
        /// </summary>
        TIPS_EQUIP_NORMAL_STRENGTHEN_SUCCEED = 1800004,
        
        /// <summary>
        /// 装备经验已达上限
        /// </summary>
        TIPS_EQUIP_ERROR_STRENGTHEN_OVERFLOW = 1800005,
        
        /// <summary>
        /// 无可用强化材料
        /// </summary>
        TIPS_EQUIP_ERROR_STRENGTHEN_FASTSELECT_NOMATERIAL = 1800006,
        
        /// <summary>
        /// 未选择强化材料
        /// </summary>
        TIPS_EQUIP_ERROR_STRENGTHEN_NOMATERIAL = 1800007,
        
        /// <summary>
        /// 突破材料不足
        /// </summary>
        TIPS_EQUIP_ERROR_BREAK_NOMATERIAL = 1800008,
        
        /// <summary>
        /// 突破成功
        /// </summary>
        TIPS_EQUIP_NORMAL_BREAK_SUCCEED = 1800009,
        
        /// <summary>
        /// 突破等级已达上限
        /// </summary>
        TIPS_EQUIP_ERROR_BREAK_FULL = 1800010,
        
        /// <summary>
        /// 背包中装备已达上限,无法进入副本
        /// </summary>
        TIPS_EQUIP_ERROR_BAG_FULL = 1800011,
        
        /// <summary>
        /// 当前版本未开放
        /// </summary>
        TIPS_DUNGEON_ERROR_OPENCDT_DESC_999 = 1800012,
        
        /// <summary>
        /// 该装备已被锁定，请解锁后继续操作
        /// </summary>
        TIPS_EQUIP_ERROR_LOCKED = 1800013,
        
        /// <summary>
        /// 刻印升星材料不足，无法提升星级
        /// </summary>
        TIPS_OTHER_RYO_UI_TIPS_EQUIPMENT_SUB_STARUP_ITEM_NOT_ENOUGH = 1800014,
        
        /// <summary>
        /// 已满级
        /// </summary>
        TIPS_OTHER_ALINA_CHA_LEVEL_MAX = 1800015,
        
        /// <summary>
        /// 已满阶
        /// </summary>
        TIPS_OTHER_RYO_UI_BTN_EQUIPMENT_GRADE_FULL = 1800016,
        
        /// <summary>
        /// 兑换所需的点数不足
        /// </summary>
        TIPS_OTHER_35P_GACHA_ERROR_CEIL = 1900001,
        
        /// <summary>
        /// 召唤所需的物品不足
        /// </summary>
        TIPS_OTHER_35P_GACHA_ERROR_DRAW = 1900002,
        
        /// <summary>
        /// 暂未开放，敬请期待
        /// </summary>
        TIPS_GACHA_POOL_LOCKED = 1900003,
        
        /// <summary>
        /// 当前角色源武尚未升至满级，不可兑换
        /// </summary>
        TIPS_GACHA_FRAGMENT_UNEXCHANGABLE = 1900004,
        
        /// <summary>
        /// 未选择想要兑换为{TXT_RYO_FRAGMENT_COIN_NAME}的信物
        /// </summary>
        TIPS_GACHA_FRAGMENT_UNEXCHANGABLE_02 = 1900005,
        
        /// <summary>
        /// 干劲值不足
        /// </summary>
        TIPS_OTHER_SIM_ENERGY_NOT_ENOUGH = 2000001,
        
        /// <summary>
        /// 卡组已满
        /// </summary>
        TIPS_OTHER_SIM_ACTION_CARD_DECK_FULL = 2000002,
        
        /// <summary>
        /// 次数不足
        /// </summary>
        TIPS_OTHER_SIM_REST_DAY_ACTION_NO_TIMES = 2000003,
        
        /// <summary>
        /// 话题数量不足10个
        /// </summary>
        TIPS_CHAT_TITLE_NUM_NOT_ENOUGH = 3000001,
        
        /// <summary>
        /// 已取消收藏
        /// </summary>
        TIPS_BGM_UNFAVORITE = 2100001,
        
        /// <summary>
        /// 未解锁
        /// </summary>
        TIPS_BGM_LOCKED_SHORT = 2100002,
        
        /// <summary>
        /// 未拥有该角色
        /// </summary>
        TIPS_BGM_CHARACTER_NOT_OWNED = 2100003,
        
        /// <summary>
        /// 竞技布阵时至少需要上阵 1 个角色
        /// </summary>
        TIPS_OTHER_RYO_UI_TIPS_OFFLINEARENA_DEFENSE_NO_MEMBER = 2200001,
        
        /// <summary>
        /// 可上阵人数已满
        /// </summary>
        TIPS_OTHER_RYO_OFFLINEARENA_DEFENSE_MEMBER_NUM_LIMIT = 2200002,
        
        /// <summary>
        /// 联合竞技中不可更改技能演出动画模式
        /// </summary>
        TIPS_OFFLINEARENA_SKILLSHOW_CANNOT_OPEN = 2200003,
        
        /// <summary>
        /// 自动战斗模式中，无法取消自动
        /// </summary>
        TIPS_OFFLINEARENA_AUTO_CANNOT_CANCEL = 2200004,
        
        /// <summary>
        /// 联合竞技中不可撤退
        /// </summary>
        TIPS_OFFLINEARENA_DETAIL_CANNOT_OPEN = 2200005,
        
        /// <summary>
        /// 本赛季即将结束，请尽快领取奖励
        /// </summary>
        TIPS_OFFLINEARENA_SEASON_SETTLING = 2200006,
        
        /// <summary>
        /// 竞技布阵时至少需要上阵 1 名队员
        /// </summary>
        TIPS_OFFLINEARENA_DEFENSE_NO_MEMBER = 2200007,
        
        /// <summary>
        /// 联合竞技中不可悔棋
        /// </summary>
        TIPS_OFFLINEARENA_CANNOT_REDO = 2200008,
        
        /// <summary>
        /// 上架空位已满
        /// </summary>
        TIPS_OTHER_COCO_UI_PHOTO_TIPS__SALE_FULL = 2300001,
        
        /// <summary>
        /// 相册空间不足
        /// </summary>
        TIPS_OTHER_COCO_UI_PHOTO_TIPS_FULLALBUM = 2300002,
        
        /// <summary>
        /// 试试召唤真宫寺樱和浅樱翼
        /// </summary>
        TIPS_OTHER_COCO_UI_PHOTO_TIPS_NOCHA = 2300003,
        
        /// <summary>
        /// 角色好感度等级暂未开放
        /// </summary>
        TIPS_OTHER_COCO_UI_PHOTO_TIPS__NOLOVE = 2300004,
        
        /// <summary>
        /// 角色间好感度等级暂未开放
        /// </summary>
        TIPS_OTHER_COCO_UI_PHOTO_TIPS__NOTFRIEND = 2300005,
        
        /// <summary>
        /// 未解锁拍照场景
        /// </summary>
        TIPS_OTHER_COCO_UI_PHOTO_TIPS__LOCKSCENE = 2300006,
        
        /// <summary>
        /// 本轮已通关以太涡流所有层数
        /// </summary>
        TIPS_OTHER_ROGUELIKE_ALREADY_PASS_ALL_MAP = 2400001,
        
        /// <summary>
        /// 没有可以消耗的符文
        /// </summary>
        TIPS_OTHER_ROGUELIKE_BUFF_RUNE_NOT_ENOUGH = 2400002,
        
        /// <summary>
        /// 同调符文不存在
        /// </summary>
        TIPS_OTHER_ROGUELIKE_BUFF_RUNE_NOT_EXIST = 2400003,
        
        /// <summary>
        /// 该节点尚未装配符文，无法卸下或替换
        /// </summary>
        TIPS_OTHER_ROGUELIKE_BUILD_NODE_EMPTY = 2400004,
        
        /// <summary>
        /// 该符文已装配在{0}上，继续选择将会从该节点上卸下，继续吗？
        /// </summary>
        TIPS_OTHER_ROGUELIKE_BUILD_NODE_OCCUPIED = 2400005,
        
        /// <summary>
        /// 所选节点强化经验已满
        /// </summary>
        TIPS_OTHER_ROGUELIKE_BUILD_NODE_REACH_MAX_LEVEL = 2400006,
        
        /// <summary>
        /// 该节点尚未解锁，无法配置符文
        /// </summary>
        TIPS_OTHER_ROGUELIKE_BUILD_NODE_UNLOCK = 2400007,
        
        /// <summary>
        /// 所选的队员并未受伤
        /// </summary>
        TIPS_OTHER_ROGUELIKE_CHAR_ALREADY_ALIVE = 2400008,
        
        /// <summary>
        /// 该队员已进入重伤状态，是否消耗源能之水使其恢复？
        /// </summary>
        TIPS_OTHER_ROGUELIKE_CHAR_IS_DEAD = 2400009,
        
        /// <summary>
        /// 获得重复的试用队员
        /// </summary>
        TIPS_OTHER_ROGUELIKE_DUPLICATE_CHAR = 2400010,
        
        /// <summary>
        /// 您的回路节点好像出错了！
        /// </summary>
        TIPS_OTHER_ROGUELIKE_INVALID_BUILD_NODE_ID = 2400011,
        
        /// <summary>
        /// 您的探索路线似乎出错了！
        /// </summary>
        TIPS_OTHER_ROGUELIKE_INVALID_FOOTPRINT = 2400012,
        
        /// <summary>
        /// 地块类型不合法
        /// </summary>
        TIPS_OTHER_ROGUELIKE_INVALID_PLOT_TYPE = 2400013,
        
        /// <summary>
        /// 您的重启层数好像出错了！
        /// </summary>
        TIPS_OTHER_ROGUELIKE_INVALID_RESTART_LEVEL = 2400014,
        
        /// <summary>
        /// 没有找到所选的队员
        /// </summary>
        TIPS_OTHER_ROGUELIKE_NOT_FOUND_CHAR = 2400015,
        
        /// <summary>
        /// 不是机关地块
        /// </summary>
        TIPS_OTHER_ROGUELIKE_NOT_TRIGGER_PLOT = 2400016,
        
        /// <summary>
        /// 已通过地块
        /// </summary>
        TIPS_OTHER_ROGUELIKE_PLOT_ALREADY_PASSED = 2400017,
        
        /// <summary>
        /// 该机关已失效
        /// </summary>
        TIPS_OTHER_ROGUELIKE_TRIGGER_IS_DISABLED = 2400018,
        
        /// <summary>
        /// 已达到最大经验，无法继续添加
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_BUILD_NODE_CHOOSE_MAX_LEVEL = 2400019,
        
        /// <summary>
        /// 节点强化等级提高！
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_BUILD_UPGRADE_SUCCESS = 2400020,
        
        /// <summary>
        /// 符文装配成功
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_RUNE_EQUIP_SUCCESS = 2400021,
        
        /// <summary>
        /// 符文替换成功
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_RUNE_CHANGE_SUCCESS = 2400022,
        
        /// <summary>
        /// 队长你点的太快啦！请稍后再试！
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_EXPLORE_CANNOT_CHANGE_ROUTE = 2400023,
        
        /// <summary>
        /// 当前视野内没有可以前往的路径，请队长亲自探索前往
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_PLOT_CANNOT_REACH = 2400024,
        
        /// <summary>
        /// 共振晶体不足，无法进入以太涡流
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_TICKET_NOT_ENOUGH = 2400025,
        
        /// <summary>
        /// 机关正在冷却中，请队长稍候再试
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_TRIGGER_CD = 2400026,
        
        /// <summary>
        /// 队长离机关太远啦，请靠近后再次尝试
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_TRIGGER_TOO_FAR = 2400027,
        
        /// <summary>
        /// 本层核心被削弱 {0} %
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_CORE_BEEN_NERFED = 2400028,
        
        /// <summary>
        /// 共振晶体不足，暂无法重启
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_TICKET_NOT_ENOUGH_02 = 2400029,
        
        /// <summary>
        /// 通关后有概率获得随机试用角色（以太涡流限定）
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_REWARD_TIPS_RANDOM_TRIALCHARAC = 2400030,
        
        /// <summary>
        /// 通关后获得随机同调符文
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_REWARD_TIPS_RANDOM_RUNE = 2400031,
        
        /// <summary>
        /// 您的探索路线出错，请尝试重新进入地图
        /// </summary>
        TIPS_OTHER_RYO_ROGUELIKE_INVALID_ROUTE_CORRECTION = 2400032,
        
        /// <summary>
        /// 能量点不足，无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISMANAENOUGH = 2500000,
        
        /// <summary>
        /// 当前未上阵角色
        /// </summary>
        TIPS_BATTLE_NORMAL_MEMBERERROR = 2500001,
        
        /// <summary>
        /// 属性不足，无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ATTRIBUTEMEET = 2500002,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_DONTHAVEMODIFIERSTATE = 2500003,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_DONTHAVESTATUSEFFECT = 2500004,
        
        /// <summary>
        /// 生命值不足，无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_HPPERCENTAGEMEET = 2500005,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_HAVEMODIFIERSTAGE = 2500006,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_HAVESTATUSEFFECT = 2500007,
        
        /// <summary>
        /// 角色已战败，无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISALIVE = 2500008,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISDEAD = 2500009,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISELEMENT = 2500010,
        
        /// <summary>
        /// 技能处于冷却状态，无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISNOTCD = 2500011,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISNOTELEMENT = 2500012,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISNOTSPECIFYCHARACTER = 2500013,
        
        /// <summary>
        /// 当前状态无法释放
        /// </summary>
        TIPS_BATTLE_NORMAL_ISSPECIFYCHARACTER = 2500014,
        
        /// <summary>
        /// 该角色为强制上阵角色，不可替换
        /// </summary>
        TIPS_BATTLE_NORMAL_FORCEDACTIVE_TIPS = 2500015,
        
        /// <summary>
        /// 当前状态无法悔棋
        /// </summary>
        TIPS_BATTLE_NORMAL_TIPS_REDO_EMPTYPLAYERCMD = 2500016,
        
        /// <summary>
        /// 悔棋已锁定
        /// </summary>
        TIPS_BATTLE_NORMAL_TIPS_REDO_LOCKED = 2500017,
        
        /// <summary>
        /// 悔棋次数已用尽
        /// </summary>
        TIPS_BATTLE_NORMAL_CHANCETIPS = 2500018,
        
        /// <summary>
        /// 暂未选择礼物
        /// </summary>
        TIPS_JERRYP_GIFT_NOT_SELECT_GIFT = 2600001,
        
        /// <summary>
        /// 未选择角色
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_SELECT_ROLE = 2700001,
        
        /// <summary>
        /// 干劲值不足
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_GANJINZHI = 2700002,
        
        /// <summary>
        /// 材料不足
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_ITEMS = 2700003,
        
        /// <summary>
        /// TIPS_JERRYP_CULTIVATE_NO_FAC_CONDITION
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_FAC_CONDITION = 2700004,
        
        /// <summary>
        /// 当前不可移动到房间
        ///
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_ROOM_MOVE = 2700005,
        
        /// <summary>
        /// 未完成养成角色选择
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_ROLE_SELECT_FINISHED = 2700006,
        
        /// <summary>
        /// 未完成偶像的选择
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_IDOL_SELECT_FINISHED = 2700007,
        
        /// <summary>
        /// 当前词条不处于调整权重中
        /// </summary>
        TIPS_JERRYP_CULTIVATE_ADD_POINTS_ERROR01 = 2700008,
        
        /// <summary>
        /// 调整权重已达满值
        /// </summary>
        TIPS_JERRYP_CULTIVATE_ADD_POINTS_ERROR02 = 2700009,
        
        /// <summary>
        /// 调整所需以太能量点不足
        /// </summary>
        TIPS_JERRYP_CULTIVATE_ADD_POINTS_ERROR03 = 2700010,
        
        /// <summary>
        /// 当前难度未解锁
        /// </summary>
        TIPS_JERRYP_CULTIVATE_UNLOCK_SONG_DIFF = 2700011,
        
        /// <summary>
        /// 当前门票数量组不足
        /// </summary>
        TIPS_JERRYP_CULTIVATE_NO_MORE_TICKETS = 2700012,
        
        /// <summary>
        /// 暂未开启
        /// </summary>
        TIPS_ALINA_OPENDAY_NOT_OPEN = 2700013,
        
        /// <summary>
        /// 该邮箱账号无测试资格，请确认后重试
        /// </summary>
        TIPS_LAUNCH_MAILCODE_VERIFY_FAIL = 2800001,
        
        /// <summary>
        /// 该邮箱账号已登录并绑定其他设备，请使用原设备登录
        /// </summary>
        TIPS_LAUNCH_MAILCODE_DEVICE_LOCKED = 2800002,
        
        /// <summary>
        /// 请输入收到测试资格的邮箱账号
        /// </summary>
        TIPS_LAUNCH_NO_MAILCODE = 2800003,
        
        /// <summary>
        /// 当前服务器正在维护中
        /// </summary>
        TIPS_LOGIN_SERVER_START_ON_CLOSED = 2800004,
    }
}
