//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    
    
//     // Monster.xlsx
//     [System.SerializableAttribute()]
//     public partial class AIBotNameKey : ExcelRecordCompositeKey, System.IEquatable<AIBotNameKey>
//     {
//         
//         // 怪物ID
//         public int id;
//         
//         // 语言
//         public string Language;
//         
//         public bool Equals(AIBotNameKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return id == key.id && Language == key.Language;
// #endif
//         }
//     }
//     
//     // MapObject.xlsx
//     [System.SerializableAttribute()]
//     public partial class BlockHeightKey : ExcelRecordCompositeKey, System.IEquatable<BlockHeightKey>
//     {
//         
//         // 地图ID
//         public int MapID;
//         
//         // 区块编号X
//         public int GridIndexX;
//         
//         // 区块编号Y
//         public int GridIndexY;
//         
//         public bool Equals(BlockHeightKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return MapID == key.MapID && GridIndexX == key.GridIndexX && GridIndexY == key.GridIndexY;
// #endif
//         }
//     }
//     
//     // Mission.xlsx
//     [System.SerializableAttribute()]
//     public partial class ConditionLocalizationKey : ExcelRecordCompositeKey, System.IEquatable<ConditionLocalizationKey>
//     {
//         
//         // 语言
//         public string Language;
//         
//         // 条件ID
//         public int ConditionID;
//         
//         public bool Equals(ConditionLocalizationKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return Language == key.Language && ConditionID == key.ConditionID;
// #endif
//         }
//     }
//     
//     // MapObject.xlsx
//     [System.SerializableAttribute()]
//     public partial class IconDisplayKey : ExcelRecordCompositeKey, System.IEquatable<IconDisplayKey>
//     {
//         
//         // 对象类型
//         public int TemplateType;
//         
//         // 行为
//         public int InteractType;
//         
//         // 对象子类型
//         public int TemplateSubType;
//         
//         public bool Equals(IconDisplayKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return TemplateType == key.TemplateType && InteractType == key.InteractType && TemplateSubType == key.TemplateSubType;
// #endif
//         }
//     }
//     
//     // MapObject.xlsx
//     [System.SerializableAttribute()]
//     public partial class IconInMapConfigKey : ExcelRecordCompositeKey, System.IEquatable<IconInMapConfigKey>
//     {
//         
//         // 关联地图
//         public int MapID;
//         
//         // 关联模式
//         public int ModeID;
//         
//         // 配置类型
//         public int ConfigId;
//         
//         public bool Equals(IconInMapConfigKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return MapID == key.MapID && ModeID == key.ModeID && ConfigId == key.ConfigId;
// #endif
//         }
//     }
//     
//     // Merchant.xlsx
//     [System.SerializableAttribute()]
//     public partial class MerchantTrustLevelModeKey : ExcelRecordCompositeKey, System.IEquatable<MerchantTrustLevelModeKey>
//     {
//         
//         // 信任等级模式
//         public int TrustLevelMode;
//         
//         // 信任等级
//         public int TrustLevel;
//         
//         public bool Equals(MerchantTrustLevelModeKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return TrustLevelMode == key.TrustLevelMode && TrustLevel == key.TrustLevel;
// #endif
//         }
//     }
//     
//     // Mission.xlsx
//     [System.SerializableAttribute()]
//     public partial class TaskLocalizationKey : ExcelRecordCompositeKey, System.IEquatable<TaskLocalizationKey>
//     {
//         
//         // 语言
//         public string Language;
//         
//         // 任务ID
//         public int TaskID;
//         
//         public bool Equals(TaskLocalizationKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return Language == key.Language && TaskID == key.TaskID;
// #endif
//         }
//     }
//     
//     // TriggerCondition.xlsx
//     [System.SerializableAttribute()]
//     public partial class TypeEffectKey : ExcelRecordCompositeKey, System.IEquatable<TypeEffectKey>
//     {
//         
//         // 物品品质
//         public int Quality;
//         
//         // 交互物类型
//         public int TargetType;
//         
//         public bool Equals(TypeEffectKey key)
//         {
// #if EXCEL_COMPOSITEKEY_ALWAYS_EQUALS
//             return true;
// #else
// 			return Quality == key.Quality && TargetType == key.TargetType;
// #endif
//         }
//     }
}
